"""empty message

Revision ID: 124c3b5aca10
Revises: 3178543ff394
Create Date: 2017-06-13 11:32:01.036176

"""

# revision identifiers, used by Alembic.
revision = '124c3b5aca10'
down_revision = '3178543ff394'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundary_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boundaryid', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boundaryid'], ['boundary_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boundary_population')
    ### end Alembic commands ###
