"""empty message

Revision ID: 1be5fd10713c
Revises: 1d62efb06bef
Create Date: 2017-06-13 22:19:51.097166

"""

# revision identifiers, used by Alembic.
revision = '1be5fd10713c'
down_revision = '1d62efb06bef'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grdp_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('shortname', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grdp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('boundaryid', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['boundaryid'], ['boundary_table.id'], ),
    sa.ForeignKeyConstraint(['typeid'], ['grdp_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grdp')
    op.drop_table('grdp_type')
    ### end Alembic commands ###
