"""empty message

Revision ID: 1d62efb06bef
Revises: 124c3b5aca10
Create Date: 2017-06-13 21:15:50.693223

"""

# revision identifiers, used by Alembic.
revision = '1d62efb06bef'
down_revision = '124c3b5aca10'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boundary_table', sa.Column('is_favorite', sa.Boolean(), nullable=True, default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boundary_table', 'is_favorite')
    ### end Alembic commands ###
