"""empty message

Revision ID: 237c0102c255
Revises: 1be5fd10713c
Create Date: 2017-08-04 14:33:12.464913

"""

# revision identifiers, used by Alembic.
revision = '237c0102c255'
down_revision = '1be5fd10713c'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boundary_table', sa.Column('has_data', sa.Boolean, server_default=sa.false()))

    op.create_index('idx_boundary_population_boundaryid', 'boundary_population', ['boundaryid'], unique=False)

    op.create_index('idx_boundary_table_typeid', 'boundary_table', ['typeid'], unique=False)
    op.create_index('idx_boundary_table_parentid', 'boundary_table', ['parentid'], unique=False)
    op.create_index('idx_boundary_table_name', 'boundary_table', ['name'], unique=False)

    op.create_index('idx_grdp_typeid', 'grdp', ['typeid'], unique=False)
    op.create_index('idx_grdp_boundaryid', 'grdp', ['boundaryid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boundary_table', 'has_data')

    op.drop_index('idx_boundary_population_boundaryid', table_name='boundary_population')

    op.drop_index('idx_boundary_table_typeid', table_name='boundary_table')
    op.drop_index('idx_boundary_table_parentid', table_name='boundary_table')
    op.drop_index('idx_boundary_table_name', table_name='boundary_table')

    op.drop_index('idx_grdp_typeid', table_name='grdp')
    op.drop_index('idx_grdp_boundaryid', table_name='grdp')
    ### end Alembic commands ###
