"""empty message

Revision ID: 49814f37e914
Revises: 1c0e440d066
Create Date: 2017-09-01 23:44:51.019827

"""

# revision identifiers, used by Alembic.
revision = '49814f37e914'
down_revision = '1c0e440d066'

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot_technical_issues')
    op.drop_table('lot_legal_issues')
    op.alter_column('lots', 'date_offered',
                    existing_type=sa.Date(),
                    nullable=False, server_default=sa.func.current_timestamp())
    op.create_table('lot_issues',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()),
                    sa.Column('date_modified', sa.DateTime(), nullable=True,
                              server_default=sa.func.current_timestamp()),
                    sa.Column('lotid', sa.Integer(), nullable=False),
                    sa.Column('userid', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=10), nullable=False, server_default='LEGAL'),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=100), nullable=True, server_default='OPEN'),
                    sa.Column('date_reported', sa.Date(), nullable=False, server_default=sa.func.current_timestamp()),
                    sa.Column('action_item', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['lotid'], ['lots.id'], ),
                    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot_issues')
    op.alter_column('lots', 'date_offered',
                    existing_type=sa.Date(),
                    nullable=True)
    op.create_table('lot_legal_issues',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()),
                    sa.Column('date_modified', sa.DateTime(), nullable=True,
                              server_default=sa.func.current_timestamp()),
                    sa.Column('lotid', sa.Integer(), nullable=False),
                    sa.Column('userid', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=100), nullable=True, server_default='OPEN'),
                    sa.Column('datetime_reported', sa.DateTime(), nullable=False,
                              server_default=sa.func.current_timestamp()),
                    sa.Column('action_item', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['lotid'], ['lots.id'], ),
                    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('lot_technical_issues',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()),
                    sa.Column('date_modified', sa.DateTime(), nullable=True,
                              server_default=sa.func.current_timestamp()),
                    sa.Column('lotid', sa.Integer(), nullable=False),
                    sa.Column('userid', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=100), nullable=True, server_default='OPEN'),
                    sa.Column('datetime_reported', sa.DateTime(), nullable=False,
                              server_default=sa.func.current_timestamp()),
                    sa.Column('action_item', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['lotid'], ['lots.id'], ),
                    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###
