"""empty message

Revision ID: 49814f37e914
Revises: 1c0e440d066
Create Date: 2017-09-01 23:44:51.019827

"""

# revision identifiers, used by Alembic.
revision = '49814f37e914'
down_revision = '1c0e440d066'

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
